[package]
name = "auth"
version = "0.0.1"
edition.workspace = true
publish.workspace = true
authors = ["SCLorentz <sclorentz@proton.me>"]

[lints]
workspace = true

[lib]
path = "src/login.rs"
doctest = false

[dependencies]
log.workspace = true
matrix-sdk.workspace = true
url.workspace = true
