[workspace]
resolver = "2"
members = [
	"crates/app",
	"crates/wt",
	"crates/renderer"
]
default-members = ["crates/wt"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
app = { path = "crates/app" }
renderer = { path = "crates/renderer" }
log = "0.4.28"
log-panics = "2.1.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.20"
url = "2.5.7"
# renderer
ash = "0.38.0"
# linux
wayland-client = "0.31"
smithay-client-toolkit = "0.18"
# macos
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
# windows
windows = { version = ">=0.59, <=0.62", features = [
	"Data_Xml_Dom",
	"Win32_Security",
	"Win32_System_Threading",
	"Win32_UI_WindowsAndMessaging",
]}


[workspace.lints.rust]
unexpected_cfgs = { level = "allow" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
