[package]
name = "dirty"
version = "0.0.1"
edition.workspace = true
publish.workspace = true
authors = ["SCLorentz <sclorentz@proton.me>"]
build = "build.rs"

[lints]
workspace = true

[lib]
path = "src/common.rs"
doctest = false

[dependencies]

[build-dependencies]
cc = "1.0"
