[package]
name = "api"
version = "0.0.1"
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/api.rs"
doctest = false

[dependencies]
log.workspace = true
matrix-sdk.workspace = true
url.workspace = true
dirty.workspace = true
